import type { Metadata } from "next";
import localFont from "next/font/local";
import "../scss/main.scss";
import "./globals.css";

const myshkin = localFont({
  src: "../fonts/Myshkin2-Regular.woff2",
  variable: "--font-myshkin",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myshkin.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
