import type { Metadata } from "next";
import localFont from "next/font/local";
import "../assets/scss/main.scss";
import "./globals.css";
import Header from "@/components/Header";

const myshkin = localFont({
  src: "../assets/fonts/Myshkin2-Regular.woff2",
  variable: "--font-myshkin",
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "MИШKiN LAБS | Sound. Code. Experiments.",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myshkin.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
